export const state = {
  mode: "national",
  chamber: "house",
  mapView: "latest_leg",
  availableMapViews: [],
  selectedState: null,
  statesGeojson: null,
  statesLayer: null,
  statesByKey: new Map(),
  stateBoundsByKey: new Map(),
  stateLayerByKey: new Map(),
  geojsonByChamber: {
    house: null,
    senate: null,
  },
  districtFeaturesByChamberState: {
    house: new Map(),
    senate: new Map(),
  },
  countyGeojson: null,
  countyFeaturesByState: new Map(),
  nhFloterialGeojson: null,
  districtLayer: null,
  districtLayerIndex: new Map(),
  floterialLayer: null,
  floterialLayerByJoinKey: new Map(),
  currentDistrictFeatures: [],
  districtNumberLayer: null,
  districtNumberBuildToken: 0,
  districtLabelRefreshToken: 0,
  selectedDistrictLayer: null,
  selectedDistrictOutlineLayer: null,
  hoverDistrictLayer: null,
  hoverInfoEl: null,
  chamberOverviewBtnEl: null,
  hasOpenPopup: false,
  countyLayer: null,
  countyLabelLayer: null,
  countyVisible: false,
  congressionalGeojsonByState: new Map(),
  congressionalLayer: null,
  congressionalLabelLayer: null,
  congressionalVisible: false,
  congressionalTargetsData: null,
  cdFilterMode: false,
  statewideMode: false,
  statewideDataByFips: new Map(),
  suspendPopupCloseOverview: false,
  targetDistrictsMode: false,
  targetFilters: {
    defense: { enabled: true, tiers: { 1: true, 2: true, 3: true, 4: true } },
    offense: { enabled: true, tiers: { 1: true, 2: true, 3: true, 4: true } },
  },
  upIn2026Mode: false,
  projectionMode: false,
  projectionBaseView: "latest_leg",
  projectionShift: 0,
  modelingVariant: "all",
  projectionPreviousUpIn2026Mode: false,
  targetJoinKeySet: new Set(),
  upIn2026JoinKeySet: new Set(),
  filteredDistrictJoinKeySet: null,
  targetDistricts: [],
  availableMapViewsByState: new Map(),
  dataByChamber: {
    house: new Map(),
    senate: new Map(),
  },
  chamberNamesByState: new Map(),
  detailsInteractionsWired: false,
  hoveredTableRowEl: null,
  hoveredStateRowEl: null,
  hoveredStateKey: null,
  hoveredStateLayer: null,
  hoveredStateOverlayLayer: null,
  nationalSort: { key: null, direction: 0 },
  detailsRenderToken: 0,
};
